In [18]:
import numpy as np

a=np.array(8)

print("Print A= ",a)

b=np.array([22,33,44,55])

print("Print B= ", b)

addition= np.add(a,b)

print("After Addition =", addition)

sub=np.subtract(b,a)

print("After Subtraction =",sub)

mul=np.multiply (a,b)

print("After Multiplcation =",mul)

div=np.divide (b,a)

print("After Division =",div)

mod=np.mod (b,a)

print("After Modulus =",mod)

Print A=  8
Print B=  [22 33 44 55]
After Addition = [30 41 52 63]
After Subtraction = [14 25 36 47]
After Multiplcation = [176 264 352 440]
After Division = [2.75  4.125 5.5   6.875]
After Modulus = [6 1 4 7]


In [14]:
import numpy as np
a= np.array([0.25,1.33,1,111])

print(a)

rec=np.reciprocal(a) 
print(rec)

[  0.25   1.33   1.   111.  ]
[4.         0.7518797  1.         0.00900901]


In [10]:
import numpy as np
a=np.array([10,100,1000])

print(a)

pow=np.power(a,2)
print("after ^2 = ", pow)


b=np.array([2,3,1])

pow1=np.power(a,b)
print("after b array elements as ^ = ", pow1)


[  10  100 1000]
after ^2 =  [    100   10000 1000000]
after b array elements as ^ =  [    100 1000000    1000]


In [9]:
import numpy as np
a= np.array ([65,55,44])
b= np.array ([6,5,4])

print("values of A=", a)
print("values of B=", b)

mm=np.mod(a,b)

rm=np.remainder(a,b)

print("Values of MODULUS = ", mm)
print("Values of REMAINDER = ", rm)



values of A= [65 55 44]
values of B= [6 5 4]
Values of MODULUS =  [5 0 0]
Values of REMAINDER =  [5 0 0]


In [7]:
import numpy as np
a=np.array([8.8j, 4.2j,11, 1+1j])
print(a)

print("Real=",np.real(a))

print("Imaginary=",np.imag(a))

print("Conjugate=", np.conj(a))

[ 0.+8.8j  0.+4.2j 11.+0.j   1.+1.j ]
Real= [ 0.  0. 11.  1.]
Imaginary= [8.8 4.2 0.  1. ]
Conjugate= [ 0.-8.8j  0.-4.2j 11.-0.j   1.-1.j ]


In [5]:
import numpy as np
a=np.array ([4.0,6.9,-2.5,8.8,60])

print(a)

print("After rounding up=", np.around(a))

print("After rounding up to 1st decimal value =", np.around(a,decimals=1))

[ 4.   6.9 -2.5  8.8 60. ]
After rounding up= [ 4.  7. -2.  9. 60.]
After rounding up to 1st decimal value = [ 4.   6.9 -2.5  8.8 60. ]


In [3]:
import numpy as np
a=np.array ([4.0,6.9,-2.5,8.8,60])

print(a)

print('\n')

print(np.floor(a))

print(np.ceil(a))

[ 4.   6.9 -2.5  8.8 60. ]


[ 4.  6. -3.  8. 60.]
[ 4.  7. -2.  9. 60.]
