In [5]:
import numpy as np
np= np.array([2,4,8])
print(np)

[2 4 8]


In [6]:
import numpy as np
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [7]:
import numpy as np
a=np.zeros(5)
print(a)

[0. 0. 0. 0. 0.]


In [8]:
import numpy as np
a=np.ones(2)
print(a)

[1. 1.]


In [14]:
import numpy as np
ab=np.empty(2)
print(ab)

[1. 1.]


In [15]:
import numpy as np
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [17]:
import numpy as np
a=np.arange(1,10,2)
print(a)

[1 3 5 7 9]


In [18]:
y = np.ones(4, dtype=int)
print(y)
y

[1 1 1 1]


array([1, 1, 1, 1])

In [19]:
arr = np.array([2,4,6,8,10,12])
print(arr)

[ 2  4  6  8 10 12]


In [22]:
a = np.array([8,16,24,32,40])
print(a)


a=np.delete(a, 0)
print(a)

[ 8 16 24 32 40]
[16 24 32 40]


In [23]:
a = np.array([11,5,2,8,6,4])
print(a)


a=np.sort(a)
print(a)

[11  5  2  8  6  4]
[ 2  4  5  6  8 11]


In [24]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
a=arr.ndim
print(arr) 
print("dimensions = ", a)

[[1 2 3]
 [4 5 6]]
dimensions =  2


In [25]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[11, 22, 33], [44, 55, 66]]])
a=arr.ndim
b=arr.size
print(arr) 
print("dimensions = ", a)
print("size = ", b)


[[[ 1  2  3]
  [ 4  5  6]]

 [[11 22 33]
  [44 55 66]]]
dimensions =  3
size =  12


In [31]:
import numpy as np
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print("Dimension = ", a.ndim)
print("Size = ",a.size)
print("Dimension = ", b.ndim)
print("Size = ",b.size)
print("Dimension = ", c.ndim)
print("Size = ",c.size)
print("Dimension = ", d.ndim)
print("Size = ",a.size)

Dimension =  0
Size =  1
Dimension =  1
Size =  5
Dimension =  2
Size =  6
Dimension =  3
Size =  1


In [50]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape) 

(2, 4)


In [29]:
a = np.arange(6)
print(a)

b = a.reshape(3,2)
print(b)

[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]
